_wandb:
    value:
        cli_version: 0.18.7
        code_path: code/scripts/main.py
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_acc
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 106
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 106
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.10.15
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 2
class_balance:
    value: false
depth_handling:
    value: max_pool
feature_config:
    value:
        - age
group_keys:
    value:
        - race
        - educat
        - gender
        - age
        - ethnic
img_size:
    value:
        - 256
        - 256
init_lr:
    value: 0.001
lungrads_path:
    value: /scratch/project2/nlst-metadata/nlst_acc2lungrads.p
max_followup:
    value: 6
nlst_dir:
    value: /scratch/project2/compressed
nlst_metadata_path:
    value: /scratch/project2/nlst-metadata/full_nlst_google.json
num_channels:
    value: 3
num_classes:
    value: 9
num_images:
    value: 200
num_workers:
    value: 8
pretraining:
    value: true
use_data_augmentation:
    value: false
valid_exam_path:
    value: /scratch/project2/nlst-metadata/valid_exams.p
